### getting request to see if it doesnt break

GET  http://localhost:3000 HTTP/1.1

### getting request for all the blog posts

GET https://jsonplaceholder.typicode.com/posts/87 HTTP/1.1


### getting all request from users

GET  http://localhost:3000/api/users HTTP/1.1

### getting request for all the blog users

GET https://jsonplaceholder.typicode.com/users/8 HTTP/1.1